version: "3.9"

services:
  backend:
    build:
      context: ./todo_backend_service
      dockerfile: Dockerfile
    image: kadince-backend:latest
    environment:
      - NODE_ENV=production
      - PORT=4000
    ports:
      - "4000:4000"
    volumes:
      - backend_data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./todo-frontend-app
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_GRAPHQL_ENDPOINT=http://18.144.65.178:4000/graphql
    image: kadince-frontend:latest
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
